### ISSUE TITLE
Free domain name

### ISSUE THREAD

**Issue by artitudinale1** [FreeCodeCampLondon/FCCLND#11]
We will need to think about a domain name were show the project possibly a free one with a good name.

@silverwedding find this good resource to check for a free domain
http://www.freenom.com/en/index.html?lang=en

I'd suggest for freecodecamplondon.cf
or freelononercampers.cf ?
Open to any suggestion / idea.....

**Comment by artitudinale1** [comment]
If we are going to use https://pages.github.com/
We could have a domain like  http://username.github.io included.
I think it would be enough even without thinking a custom domain name.

Once we are on a stage we can go live - I ll move this repo to https://github.com/FreeCodeCampLondon 
So we could have : FreeCodeCampLondon.github.io - which sounds good to me.

Then we can clone repo and keep working to switch backend from Firebase to use Nodejs and stuff. What you think?

**Comment by chris-alexander** [comment]
Sounds good to me! Do you think I should shorten our org name from `FreeCodeCampLondon` to `FCCLondon` or `FCCLDN` or even `LondonCampers` or something to save typing? We can still get a free domain name and use a CNAME file with gh-pages. If the intention is to go full-stack at some point we will have to move from gh-pages because it has no 'backend' per se: it just serves static assets. I think the only free option for this is Heroku, but we can work on that when we get there :)

**Comment by artitudinale1** [comment]
Yeah absolutely we can see in the future. For the moment github and Firebase would be just fine.
To me FreeCodeCampLondon is ok , true a little bit of typing but it's clear and official. 
I'm open to any other idea or option eventually.
